config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :categories

  root 'articles#index'
  resources :articles
  namespace :api do
    resources :articles do

      member do
        get "categories" #/api/articles/:id/categories
      end

      collection do
        get 'categories2' #/api/articles/categories2
      end

    end
  end

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/article.rb
class Article < ActiveRecord::Base

	belongs_to :user
	has_and_belongs_to_many :categories

	has_attached_file :imagen, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  	validates_attachment_content_type :imagen, :content_type => /\Aimage\/.*\Z/

	validates :name,  presence: true, uniqueness: true
	validates :description,  presence: true
	validates :price,  presence: true
	#validates_presence_of :name,  message:"No debe de estar vacio"
	scope :ordenados, -> { order("created_at DESC")}

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_and_belongs_to_many :articles
	validates :name, presence: true, uniqueness: true
	validates :color, presence: true, uniqueness: true
end

app/models/user.rb
class User < ActiveRecord::Base
	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable, :registerable,
	:recoverable, :rememberable, :trackable, :validatable

	has_many :articles
end

app/controllers/api/articles_controller.rb
class Api::ArticlesController < ApplicationController
	def index
		render :json => {
			:message => " Esto fuinciona yeiii!!! :D",
			:articles => Article.all
		 }
	end
	def categories
		render :json => {
			:categories => Article.find(params[:id]).categories
		}
	end
	def categories2
		render :json => {
			:categories => Category.all
		}
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_action :authenticate_user!, except: [:index, :show]
	before_action :categories, only: [:create, :update]

	#layout 'base', except: [:show]
	#layout 'base', only: [:show]

	#get /articles
	def index
		@articles = Article.all.ordenados
	end

	#get /articles/new
	def new
		@article = Article.new
	end

	#get /articles/:id
	def show
		@article = Article.find(params[:id])
	end

	#put /articles/:id
	#patch /articles/:id
	def update
		@article = Article.find(params[:id])
		if @article.update_attributes(article_params )
			@article.categories = @categories
			redirect_to @article
		else
			render :edit
		end
	end


	#post /articles
	def create
		@article = current_user.articles.new(article_params)
		#@article = Article.new(article_params)
		if @article.save
			@article.categories = @categories
			redirect_to @article
		else
			render :new
		end
	end

	#get /articles/:id/edit
	def edit
		@article = Article.find(params[:id])
	end

	#delete /articles/:id
	def destroy
	end

	private
	def article_params
		params.require(:article).permit(:name, :description, :price, :imagen)
	end

	def categories
		unless params[:article][:category_ids].nil?
			 @categories = params[:article][:category_ids].map{|k, v| Category.find(k)}
		else
			@categories = []
		end
	end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

	before_action :authenticate_user!, except: [:index, :show]

	before_action :set_category, only: [:show, :edit, :update, :destroy]

	# GET /categories
	# GET /categories.json
	def index
		@categories = Category.all
	end

	# GET /categories/1
	# GET /categories/1.json
	def show
	end

	# GET /categories/new
	def new
		@category = Category.new
	end

	# GET /categories/1/edit
	def edit
	end

	# POST /categories
	# POST /categories.json
	def create
		@category = Category.new(category_params)

		respond_to do |format|
			if @category.save
				format.html { redirect_to @category, notice: 'Category was successfully created.' }
				format.json { render :show, status: :created, location: @category }
			else
				format.html { render :new }
				format.json { render json: @category.errors, status: :unprocessable_entity }
			end
		end
	end

	# PATCH/PUT /categories/1
	# PATCH/PUT /categories/1.json
	def update
		respond_to do |format|
			if @category.update(category_params)

				format.html { redirect_to @category, notice: 'Category was successfully updated.' }
				format.json { render :show, status: :ok, location: @category }
			else
				format.html { render :edit }
				format.json { render json: @category.errors, status: :unprocessable_entity }
			end
		end
	end

	# DELETE /categories/1
	# DELETE /categories/1.json
	def destroy
		@category.destroy
		respond_to do |format|
			format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
			format.json { head :no_content }
		end
	end

	private
		# Use callbacks to share common setup or constraints between actions.
		def set_category
			@category = Category.find(params[:id])
		end

		# Never trust parameters from the scary internet, only allow the white list through.
		def category_params
			params.require(:category).permit(:name, :color)
		end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/api/articles_helper.rb
module Api::ArticlesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_article.html.erb
<article class="article">
	<figure>
		<%= image_tag article.imagen.url %>

	</figure>
	<a href="/articles/<%= article.id%>">
		<h3><%= article.name%></h3>
		<p><%= article.description%></p>
	</a>

	<% article.categories.each do |category| %>

	<span class="data-category">
		<%= link_to category.name, category_path(category), style: "color: #{category.color}"%>
	</span>

	<%end%>
	<span class="data-price">
		<b>Precio</b>
		<span class="price">$<%= article.price%></span>
	</span>
</article>

app/views/articles/_form.html.erb
<%=form_for(@article) do |f|%>




<ul>
	<% @article.errors.full_messages.each do |msg|%>
	<li class="errors"><%= msg %></li>
	<%end%>
</ul>




<div class="field">
	<%= f.text_field :name, placeholder:"Nombre del Articulo", class: "form-control" %>
</div>
<div class="field">
	<%= f.text_area :description, placeholder:"Descripción del Articulo", class: "form-control" %>
</div>
<div class="field">
	<%= f.number_field :price, placeholder:"Precio del Articulo", class: "form-control" %>
</div>
<div class="field">
	<%= f.file_field :imagen %>
</div>



<div class="field">
	<% Category.all.each do |c| %>
	<div class="checkboxes">
		<label>
			<%= check_box_tag "article[category_ids][#{c.id}]",
			nil,
			@article.categories.member?( c ) %>
			<%= c.name%>
		</label>
	</div>
	<%end%>

</div>



<div class="field">
	<%= f.submit "Guardar", class: "btn btn-success"%>
</div>

<% end %>

app/views/articles/edit.html.erb
<section class="title">
	<h2>Editar Articulo</h2>
</section>
<%= render 'form' %>

app/views/articles/index.html.erb
<section class="title">
	<h2>
		Lista de articulos
		<% if user_signed_in?%>
		<%= link_to "+", new_article_path, class: "btn btn-success" %>
		<% end %>
	</h2>
	<p id="notice"><%#= notice %></p>
</section>

<section class="col-md-12">

	<% @articles.each do |article| %>
	<%= render "article", article: article %>
	<%end %>
</section>

app/views/articles/new.html.erb
<section class="title">
	<h2>Crear articulo</h2>
</section>
<%= render 'form' %>

app/views/articles/show.html.erb
<article class="article-details">
	<div class="article-image">
		<%= image_tag @article.imagen.url %>
	</div>
	<div class="article-data">
		<div class="data-info">
			<h3>Nombre:</h3>
			<span><%= @article.name %></span>
		</div>
		<div class="data-info">
			<h3>Descripción:</h3>
			<span><%= @article.description %></span>
		</div>
		<div class="data-info">
			<h3>Categorias:</h3>

			<% @article.categories.each do |category| %>

			<span><%= category.name%></span>

			<%end%>

		</div>
		<div class="data-info">
			<h3>Precio:</h3>
			<span>$<%= @article.price %></span>
		</div>



		<% unless @article.user.nil? %>

		<div class="data-info">
			<h3>Usuario:</h3>
			<span><%= @article.user.email %></span>
		</div>
		<%end%>
		<div class="data-info">
			<h3>categorias</h3>

		</div>

	</div>

	<div class="btns">
		<%= link_to "Editar", edit_article_path(@article), class: "btn btn-info" %>
	</div>
</article>

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :name, placeholder:"Nombre", class:"form-control" %>
  </div>
  <div class="field">
    <%= f.color_field :color %>
  </div>
  <div class="field">
    <%= f.submit "Guardar", class:"btn btn-success"%>
  </div>
<% end %>

app/views/categories/edit.html.erb
<div class="title">

<h2>Editing Category</h2>
</div>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>
<section class="title">
	<h2>
		Lista de categorias
		<% if user_signed_in?%>
		<%= link_to "+", new_category_path, class: "btn btn-success" %>
		<% end %>
	</h2>
</section>
<div class="col-md-12">
	<table class="table table-striped table-bordered">
		<thead>
			<tr>
				<th>Name</th>
				<th>Color</th>
				<th></th>
			</tr>
		</thead>

		<tbody>
			<% @categories.each do |category| %>
			<tr>
				<td><%= category.name %></td>
				<td><span class="show-color" style="background:<%= category.color %>;"></span> </td>
				<td>
					<%= link_to 'Show', category, class:"btn btn-info" %>
					<%= link_to 'Edit', edit_category_path(category) , class:"btn btn-success"%>
					<%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %>
				</td>
			</tr>
			<% end %>
		</tbody>
	</table>
</div>

app/views/categories/new.html.erb
<div class="title">
<h2>New Category</h2>

</div>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<section class="title">
	<h2>
  <%= @category.name %>
	</h2>
</section>
<section class="col-md-12">
	<% @category.articles.ordenados.each do |article|%>
	<%= render "articles/article", article: article %>
	<% end%>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Tiendita</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
</head>
<body>

	<header>
		<a href="/" class="logo">
			Mi tiendita
		</a>
		<nav>
			<ul>
				<li>
					<a href="/articles">Articulos</a>
				</li>
				<li>
					<a href="/categories">Categorias</a>
				</li>
			</ul>
		</nav>

		<div class="user-controls" style="">
			<ul>
				<% if user_signed_in? %>
				<li>Bienvenido <%= current_user.email %></li>
				<li>
					<%= link_to "Cerrar sesión", destroy_user_session_path, method: :delete %>
				</li>
				<% else %>
				<li>
					<%= link_to "Iniciar sesión", new_user_session_path %>

				</li>
				<li>
					<%= link_to "registrate", new_user_registration_path %>
				</li>
				<% end%>
			</ul>
		</div>
	</header>
	<section class="main">
		<%if notice || alert %>
		<div class="notifications">
			<p class="notice"><%= notice %></p>
			<p class="alert"><%= alert %></p>
		</div>
		<%end%>

		<%= yield %>
	</section>
	<footer>
		<div class="text-center">
			Curso Ruby on Rails
		</div>
	</footer>
</body>
</html>

app/views/layouts/base.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mitiendita</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body style="background: gray">

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<div class="title">
	<h2>Bienvenidos al curso de RoR</h2>
</div>